config/routes.rb
Rails.application.routes.draw do
  root 'viewer#ptedit'

  namespace :api do
    get  'search',  to: 'arcanas#search'
    get  'ptm',     to: 'arcanas#ptm'
    get  'codes',   to: 'arcanas#codes'
    get  'name',    to: 'arcanas#name_search'
    post 'request', to: 'arcanas#request_mail'
  end

  get  'cc3',        to: 'viewer#cc3'
  get  'about',      to: 'viewer#about'
  get  'changelogs', to: 'viewer#changelogs'
  get  'db',         to: 'viewer#database'
  get  'data/:code', to: 'viewer#detail'
  get  'data/:code/:name', to: 'viewer#detail'
  get  ':code', to: 'viewer#ptedit', code: /[A-Z0-9]+/
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Author" content="ぱろっと" />
    <meta name="keywords" content="チェンクロ,チェインクロニクル,パーティー,アルカナ,検索,シミュレーター,パーティーシミュレーター" />
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Pragma" content="no-cache">
    <meta property="og:site_name" content="<%= site_title %>" />
    <meta property="og:title" content="<%= "#{truncate(@title, length: 30)} : " unless @title.blank? %><%= site_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="<%= asset_pack_path 'images/ccpts.png' %>" />
    <meta property="og:url" content="<%= @uri %>" />
    <meta property="og:description" content="チェンクロのパーティーを構成したり共有したりできます。アビリティや必殺技からのアルカナ検索も可能" />
    <meta name="twitter:site" content="@parrot_studio">
    <meta name="twitter:card" content="summary">
    <link rel="canonical" href="<%= @uri %>" />
    <link itemprop="author" href="https://twitter.com/parrot_studio" />
    <title><%= "#{truncate(@title, length: 30)} : " unless @title.blank? %><%= site_title %></title>
    <%= stylesheet_pack_tag 'application' %>
    <link rel="shortcut icon" type="image/x-icon" href="<%= asset_pack_path 'images/favicon.ico' %>" />
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wallpaper"></div>
    <div class="container">

      <div class="row">
        <div class="hidden-xs hidden-sm col-md-1"></div>

        <div class="col-xs-12 col-sm-12 col-md-10">
          <%= yield %>
        </div>

        <div class="hidden-xs hidden-sm col-md-1"></div>
      </div>
    </div>

    <div>
      <footer>
        <p class="small">
          <strong>チェインクロニクル</strong> &copy; SEGA <%= link_to 'http://chronicle.sega-net.com/', 'http://chronicle.sega-net.com/' %>
        </p>
        <p class="text-muted small">
          作った人 : ぱろっと（<%= link_to '@parrot_studio', 'https://twitter.com/parrot_studio/', :target => '_blank' %>）
        </p>
        <p class="small">
          <%= link_to 'もっと細かい説明', about_path %> / <%= link_to '過去の更新履歴', changelogs_path %>
        </p>
        <p class="text-muted small">
          ご意見・要望・質問等はこちらから<br>
          Twitter : <%= render 'viewer/tweet' %><br>
          Blog : <%= link_to 'http://netgamer.hateblo.jp/', 'http://netgamer.hateblo.jp/', :target => '_blank' %>
        </p>
      </footer>

      <% if show_ads?(@ptm) %>
        <div id="ads">
          <hr />
          <%=raw amazon %>
          <%=raw adsense %>
        </div>
      <% end %>
    </div>

    <%= javascript_pack_tag 'application' %>
    <script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
    <% cache do %>
      <%=raw analytics %>
    <% end %>
  </body>
</html>